<a href="https://colab.research.google.com/github/champsleague/DeepLearning/blob/main/DL_wk1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!cat /proc/meminfo

MemTotal:       13297200 kB
MemFree:         9619816 kB
MemAvailable:   12389068 kB
Buffers:          227492 kB
Cached:          2717176 kB
SwapCached:            0 kB
Active:           423880 kB
Inactive:        2982160 kB
Active(anon):       1024 kB
Inactive(anon):   450488 kB
Active(file):     422856 kB
Inactive(file):  2531672 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:             28672 kB
Writeback:             0 kB
AnonPages:        461452 kB
Mapped:           252252 kB
Shmem:              1336 kB
KReclaimable:     112352 kB
Slab:             143020 kB
SReclaimable:     112352 kB
SUnreclaim:        30668 kB
KernelStack:        4224 kB
PageTables:         6092 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6648600 kB
Committed_AS:    2599128 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       68140 kB
VmallocChunk:          0 kB
Percpu:          

In [1]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
addres

In [2]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets

In [4]:
# 1D Array with Pytorch

import torch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [7]:
print(t.dim()) #rank
print(t.shape) #shape
print(t.size()) #size
print(t[0], t[1], t[-1]) #Element
print(t[2:5], t[4:-1]) #Slicing
print(t[:2], t[3:]) #Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [8]:
# 2D Array with Pytorch

t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [19]:
print(t.dim())
print(t.size())  #shape
print(t[:,1])
print(t[:,1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [22]:
import numpy as np

t = np.array([[[0,1,2],
              [3,4,5]],
             
             [[6,7,8],
              [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)


import torchvision

t2 = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
ft2 = torch.from_numpy(t2).float()

print(ft2.shape)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])


In [24]:
# Broadcasting

import numpy as np
import torch

# Same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [26]:
# Vector + Scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1)
print(m2)
print(m1+m2) # m2:3 -> [[3,3]]

tensor([[1., 2.]])
tensor([3.])
tensor([[4., 5.]])


In [27]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1)
print(m2)
print(m1+m2)


tensor([[1., 2.]])
tensor([[3.],
        [4.]])
tensor([[4., 5.],
        [5., 6.]])


In [30]:
#Mul vs Matmul

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

print("\n")

m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1 : ',m1.shape)
print('Shape of Matrix 2 : ',m2.shape)
print(m1*m2)
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


Shape of Matrix 1 :  torch.Size([2, 2])
Shape of Matrix 2 :  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [32]:
# Mean

t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [33]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])
